apiVersion: v2
appVersion: 'Qwen/Qwen3-Coder-32B-Instruct-AWQ'
description: Helm chart for Qwen3-Coder 32B model serving with vLLM
name: vllmqwen3coder32binstruct4bit
type: application
version: '1.0.0'
