apiVersion: v2
appVersion: 'qwen3-vl:30b-a3b-instruct-fp8'
description: Helm chart for Qwen3-VL 30B A3B Instruct FP8 model serving with Ollama
name: ollamaqwen3vl30ba3bfp8
type: application
version: '1.0.0'
