apiVersion: v2
appVersion: 'hf.co/Kijai/flux-fp8:flux1-schnell-fp8-e4m3fn.safetensors'
description: Helm chart for FLUX.1 schnell FP8 image generation model serving with Ollama
name: ollamaflux1schnellfp8
type: application
version: '1.0.0'
