apiVersion: v2
appVersion: 'hf.co/black-forest-labs/FLUX.2-klein-9B'
description: Helm chart for FLUX.2 Klein 9B image generation model serving with Ollama
name: ollamaflux2klein9b
type: application
version: '1.0.0'
